### ISSUE TITLE
Replace ampersands with XML entities (&amp;)

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-ulysses-tei#13]
Other characters are better off in unicode, for readability's sake, but ampersands are throwing off the validation. For this reason, we should replace all instances of `&` with the XML code `&amp;`, which will then be rendered as `&`. This seems to be mostly "professor of dancing &tc." in Wandering Rocks. I'll go ahead and do this on the `validate` branch.

**Comment by yellwork** [comment]
Nice. I spotted the troublesome &s in WR (three of them, right?). I don’t think any other episode has a single ampersand.
