### ISSUE TITLE
changed -- to a spaced en dash

### ISSUE THREAD

**Issue by yellwork** [open-editions/corpus-joyce-ulysses-tei#15]
I realised, as I was making this change, that it should have been introduced as an issue first of all. Sorry, guys. Here’s the phenomenon and my response. More than willing to hear different perspectives.

Our markup had a lot of double hyphens to indicate asides, for example:

```xml
<lb n="160955"/>large way of business if -- a big if, however -- he had contrived to cure
```

which I changed globally to 

```xml
<lb n="160955"/>large way of business if – a big if, however – he had contrived to cure
```

i.e. A spaced en dash according to the Irish/UK convention. Is that Joyce’s convention?

Edge-cases:
The censorship at 18.490 –

```xml
<lb n="180490"/>bumgut fell out a nice word for any priest to write and her a--e as if any
```

– I changed to an em dash:

```xml
<lb n="180490"/>bumgut fell out a nice word for any priest to write and her a—e as if any
```

But what about this?

```xml
<p rend="inset"><lb n="090500"/><foreign xml:lang="la">Glo-o--ri--a in ex--cel--sis De--o.</foreign></p>
```

Or the moment where a narrator in ‘Oxen’ breaks off, mid-sentence?

```xml
<lb n="140796"/>tipped with her tongue the outer chamber of my ear), the first is a bath –
<lb n="140797"/>But at this point a bell tinkling in the hall cut short a discourse which
```

**Comment by JonathanReeve** [comment]
Looks great. I'll go ahead and close this issue, then, since it's complete. Thanks for opening it, though, as it'll be good record to have.
