### ISSUE TITLE
Marking up unitalicized titles?

### ISSUE THREAD

**Issue by c-forster** [open-editions/corpus-joyce-ulysses-tei#18]
In "Telemachus" there are works mentioned that are not currently marked up, because they are not italicized in the print edition, and so were not marked up with `<emph>` tags. For instance:

```xml
Can you recall, brother, is mother Grogan's tea and water pot spoken of
<lb n="010371"/>in the Mabinogion or is it in the Upanishads?</said>
```

I marked this up as follows in #17196501040 (I caught it incidentally and only remembered after the PR; apologies for confounding two issues in one PR):

```xml
Can you recall, brother, is mother Grogan's tea and water pot spoken of
<lb n="010371"/>in the <title rend="none">Mabinogion</title> or is it in the <title rend="none">Upanishads</title>?</said>
```

Is that a reasonable way to handle this? There does not yet seem to be a title `type` applicable to these works. There are also references to *Hamlet* that might be applicable here; though it is conceivable that the reference is to the character, I think the following should also be marked up *if* we're marking up typographically unmarked titles:

```xml
<lb n="010487"/><said who="Buck Mulligan">―Wait till you hear him on Hamlet, Haines.</said>
[...]
<lb n="010545"/><said who="Haines">―What is your idea of Hamlet?</said> Haines asked Stephen.
```

**Comment by yellwork** [comment]
Good call. That’s consistent with what we’ve been proposing for unmarked instances of `<foreign>` and `<name>`. There will be others, I’m sure.

It might be wishful thinking if we imagine that we’re going to catch everything, but we should certainly (eventually) aim to run all _marked_ instances of a given `<title>` or `<name>` or whatever against the rest of the corpus to turn up unmarked instances. These should be encoded with the `@rend="none"` attribute. So (per #10) we can run `<name type="horse">Throwaway</name>`, for example, against the rest of the corpus to find all unmarked instances of the horse’s name appearing.

**Comment by JonathanReeve** [comment]
Since this issue looks settled, I've just added this convention to CONTRIBUTING.md (see https://github.com/JonathanReeve/corpus-joyce-ulysses-tei/commit/953a5e12276a3ab157c4a25ea93d7b0b7af147aa#diff-6a3371457528722a734f3c51d9238c13R55), so that we can close this issue. Feel free to reopen later, though, if edge cases come up.
