### ISSUE TITLE
Move @who attributes from <speaker> to <sp> for dramatic segments

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-ulysses-tei#21]
While validating our codebase against the DTD, the validator complains that `<speaker>` tags shouldn't have `who` attributes. I did a little looking around, and it looks like `<sp>`s can take them. The [TEI docs](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-sp.html) for `<sp>`s note: "the who attribute on this element may be used either in addition to the speaker element or as an alternative." Since Joyce's speaker headings aren't always regular ("Mageeglinjohn" at 090900, for instance), it makes sense to use `<sp who="">` in addition to `<speaker>`. The markup would then be a change from: 

```xml
<sp><speaker who="John Eglinton"><lb n="090900"/>Mageeglinjohn</speaker>
<p><lb n="090901"/>Names! What's in a name?</p></sp>
```

to: 

```xml
<sp who="John Eglinton"><speaker><lb n="090900"/>Mageeglinjohn</speaker>
<p><lb n="090901"/>Names! What's in a name?</p></sp>
```

I'll go ahead and do this, if there are no objections. Then I think we'll be fully valid, against the DTD, at least.

**Comment by yellwork** [comment]
Hell, I really dropped the ball yesterday. Good catch, Jonathan – and at least you spotted this before we tackled the `@who` tagging for “Circe”!

Go ahead, I say, and make the changes in “S & C.”
