### ISSUE TITLE
Merge with Portrait project

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-ulysses-tei#28]
Maybe create an umbrella organization on GitHub first?

**Comment by yellwork** [comment]
This issue can be closed now, right?

**Comment by JonathanReeve** [comment]
Yep, I think so. Ideally, we'd have some sort of way to avoid haing redundant Travis / XSL / other code that's shared between the two projects, but I don't know of a simple way to do that at the moment. Closing.
