### ISSUE TITLE
Deposit with institutional storage

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-ulysses-tei#29]
ModNets recommends that we back up the project periodically to an institutional repository. Columbia Academic Commons? [Open Science Framework](https://osf.io/)?

**Comment by JonathanReeve** [comment]
This is a really interesting and complicated problem, it looks like. OSF has GitHub integration, but it's not backed up to their systems by default. To get it to back up from GitHub automatically, it'd be a matter of writing something to interface with [their API](https://developer.osf.io/#Introduction_attribute_validation). Columbia Academic Commons says they only accept "finished" projects, but as an ever-evolving project, this would technically never be finished, since there'd always be something it'd be possible to add. It *might* be possible to script a periodic submission to CAC or to the MLA CORE (@rekmla?) but difficult. I'll keep looking into this.

**Comment by JonathanReeve** [comment]
It looks like [Zenodo](https://zenodo.org/) can do what we need. It operates on releases, so we'd first need to create numbered releases (it doesn't really matter what state they're in). Probably best to merge the two editions under an umbrella organization, first. Then these two editions will get a DOI!

**Comment by tcatapano** [comment]
@JonathanReeve: my organization Plazi uses and works closely with the developers/maintainers of Zenodo (we manage https://zenodo.org/communities/biosyslit/). Please let me know if you have any questions or need any help with it. Would be happy to help.

**Comment by JonathanReeve** [comment]
Thanks @tcatapano! I just got it set up, so now we should have backups at Zenodo. Now all I have to do is remember to make a new release every now and then. It's nice having DOIs for these projects!
