### ISSUE TITLE
Using <lg> over <p> for offset poetry?

### ISSUE THREAD

**Issue by yellwork** [open-editions/corpus-joyce-ulysses-tei#31]
In the course of disambiguating some lingering `<emph>` encodings in the episodes, I have been thinking about the way we encode all the inset, typographically offset poetry. Here’s an example from “Telemachus”:
```xml
<p rend="inset"><lb n="010264"/><quote>And no more turn aside and brood.</quote></p>
```
Really, though, why would we be calling this a `<p>`? Shouldn’t it be a one-line `<lg>`?
Or, better yet, take this example from “Proteus”:
```xml
<p rend="inset"><lb n="030021"/><emph>Won't you come to Sandymount,
<lb n="030022"/>Madeline the mare?</emph></p>
```
We can’t use `<quote>` to disambiguate the `<emph>` tagging here because, so far as we know, this is Stephen’s own doggerel verse.
What about something like:
```xml
<lg rend="italics"><lb n="030021"/><l>Won't you come to Sandymount,</l>
<lb n="030022"/><l>Madeline the mare?</l></lg>
```

What do you guys think?
I’ve tried out this new encoding in “Proteus,” but I’m happy to revert /refine further if I’ve missed something. I’m wondering too how the example from “Telemachus” might be better encoded:
```xml
<lg><lb n="010264"/><l><quote>And no more turn aside and brood.</quote><l></lg>
```

**Comment by JonathanReeve** [comment]
Sounds great! You're totally right, these should be `<lg>`s instead of `<p>`s. 

As an aside, I'd always instinctively assumed that "Madeline the mare" is a quote of some sort, but I guess it's not! At least, not one that I can find in Google Books or via Gifford. I did find [this note](http://m.joyceproject.com/notes/030127madelinethemare.html), though. This is the first time that I've seen [The Joyce Project](http://www.joyceproject.com/)--looks interesting! I wonder if there's a way we could join forces with some of these Ulysses notes sites (there's another ancient one [here at Columbia](http://www.columbia.edu/~fms5/ulys.htm), and incorporate explanatory notes in the text in some way, or at least links to external pages. Not a pressing issue at all, but something to keep thinking about, maybe.

**Comment by yellwork** [comment]
> I'd always instinctively assumed that "Madeline the mare" is a quote of some sort

Me too, but computer says _No_. I’ve had my eye on the Joyce Project as well – I was thinking it’d be nice to integrate their work on People in the Novel into our data (esp. as we work on our `@who` values). We might reach out further down the line?

How does this nesting look for `<lg>`s?

```xml
<lg rend="italics">
     <lb n="070522"/><l>On swift sail flaming</l>
     <lb n="070523"/><l>From storm and south</l>
     <lb n="070524"/><l>He comes, pale vampire,</l>
     <lb n="070525"/><l>Mouth to my mouth.</l>
</lg>
```
The `@rend` value might have to record spacing and inset rather than italics, I suppose.
And for lines we’re certain form a quotation:
```xml
<quote>
     <lg rend="italics">
     <lb n="090137"/>
          <l>Whelps and dams of murderous foes whom none</l>
          <lb n="090138"/><l>But we had spared ....</l>
     </lg>
</quote>
```
I figure the ellipsis should be part of the `<l>`, by the bye, even though that changes the inherited (typographic) encoding slightly.

The final case I can think of right now is a bit more complicated. Mulligan is reciting Yeats’s poetry here:

```xml
<p>
     <lb n="010237"/>His head vanished but the drone of his descending voice boomed out <lb n="010238"/>of the stairhead:
     <lb n="010239"/>
     <said who="#bm">―
          <quote>
               <lg rend="italics">
                    <l>And no more turn aside and brood</l>
                    <lb n="010240"/><l>Upon love’s bitter mystery</l>
                    <lb n="010241"/><l>For Fergus rules the brazen cars.</l>
               </lg>
          </quote>
     </said>
</p>

```
Not sure what to do with that dialogue dash… Part of the first `<l>`?

**Comment by JonathanReeve** [comment]
I think this one is done, no? Closing, but feel free to reopen otherwise.
