### ISSUE TITLE
Fixing Travis

### ISSUE THREAD

**Issue by charlesreid1** [open-editions/corpus-joyce-ulysses-tei#37]
It appears the Travis CI system is broken, because it is looking for the repository JonathanReeve/corpus-joyce-ulysses-tei instead of open-editions/corpus-joyce-ulysses-tei. The Travis page states the repo is missing: https://travis-ci.org/JonathanReeve/corpus-joyce-ulysses-tei

@JonathanReeve would it be possible for you to update this when you get some time?

**Comment by JonathanReeve** [comment]
It looks like Travis has moved to a new Ubuntu machine which didn't have `xmllint`. I added an `apt` line or two to fix this. This should be all set now. The build is failing at the moment because of a DTD error, but at least it's failing correctly! :sweat_smile:

**Comment by JonathanReeve** [comment]
Oh, I should say, the Travis builds are now at https://travis-ci.org/open-editions/corpus-joyce-ulysses-tei. I should update the links in the README to reflect that.

**Comment by charlesreid1** [comment]
Cool! Thanks for the fix. I'll see if I can't get that DTD issue fixed now...
