### ISSUE TITLE
Reorder tags in Circe

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-ulysses-tei#8]
Here's Ronan's description of the issue: 

Joshua and I realized `<lb/>`s should only be placed at the beginning of the first textual unit of a given line (i.e. preceding the first character of the first word). All tagging that also opens at that line – whether a `<p>`,  `<head>`, `<sp>` etc. – should also precede the `<lb/>`.

What needs to change for ‘Circe’, then, is swapping the order of any lead `<lb/>` tag that is followed immediately by another TEI element or elements. The `<lb/>` needs to go deeper into the nesting, rather than standing outside of it.

This has already been done by HWG for the `<p><lb/>` pairing but, in practice, these are the cases we now need to address:

Standalone stage directions: All `<lb n="15xxxx"/><stage>` → `<stage><lb n="15xxxx"/>`. The opening `<stage>` tag should precede the first `<lb/>` for each stage direction.
Stage directions within character speeches: All `<p><lb n="15xxxx"/><stage>` → `<p><stage><lb n="15xxxx"/>`. The opening `<stage>` tag should precede the first `<lb/>` for each stage direction but follow the opening `<p>` tag. (In practice, this is the same conversion as Case 1 above, but just takes place deeper into the nesting.)

Character speeches: All `<lb n="15xxxx"/><sp><speaker>` → `<sp><speaker><lb n="15xxxx"/>`. Both the opening `<sp>` and `<speaker>` (in that order) should precede the first `<lb/>` for each character speech.

Here are some examples from the episode just to make clear(er) what I mean.

At the moment, we have the following encoding convention for standalone stage directions:

```xml
<lb n="150014"/><stage>(A deafmute idiot with goggle eyes, his shapeless mouth dribbling, 
<lb n="150015"/>jerks past, shaken in Saint Vitus' dance. A chain of children's hands 
<lb n="150016"/>imprisons him.)</stage>
```

When what I believe we actually want is the following:

```xml
<stage><lb n="150014"/>(A deafmute idiot with goggle eyes, his shapeless mouth dribbling, 
<lb n="150015"/>jerks past, shaken in Saint Vitus' dance. A chain of children's hands 
<lb n="150016"/>imprisons him.)</stage>
```

Individual character speeches currently look like this:

```xml
<lb n="150010"/><sp><speaker>The Call</speaker>
<p><lb n="150011"/>Wait, my love, and I'll be with you.</p></sp>
<lb n="150012"/><sp><speaker>The Answer</speaker>
<p><lb n="150013"/>Round behind the stable.</p></sp>
```

When what we want is this:

```xml
<sp><speaker><lb n="150010"/>The Call</speaker>
<p><lb n="150011"/>Wait, my love, and I'll be with you.</p></sp>
<sp><speaker><lb n="150012"/>The Answer</speaker>
<p><lb n="150013"/>Round behind the stable.</p></sp>
```

Character speeches with stage directions in the dialogue currently look like this:

```xml
<lb n="150019"/><sp><speaker>The Idiot</speaker>
<p><lb n="150020"/><stage>(lifts a palsied left arm and gurgles)</stage> Ghahute!</p></sp>
```

When what we want is this:

```xml
<sp><speaker><lb n="150019"/>The Idiot</speaker>
<p><stage><lb n="150020"/>(lifts a palsied left arm and gurgles)</stage> Ghahute!</p></sp>
```

**Comment by yellwork** [comment]
Looks great, Jonathan. I vote for going ahead and reordering the tagging. This issue can stand as our documenting rationale.

**Comment by JonathanReeve** [comment]
I think I've fixed this one. Take a look and let me know what you think. If there's still something that needs to be done with this, feel free to reopen this issue.

**Comment by yellwork** [comment]
Looks terrific, Jonathan!

The only thing I can think of—and this only occurred to me after I opened the episode in oXygen: sorry—is the cases where `<foreign>` or a residual, yet-to-be-disambiguated `<emph>` begins the reading-text line. For example(s):

```xml
<p><lb n="150077"/><foreign xml:lang="la">Vidi aquam egredientem de templo a latere dextro. Alleluia.</foreign></p></sp>
<p><lb n="150170"/><foreign xml:lang="la">Aurora borealis</foreign> or a steel foundry? Ah, the brigade, of course. South side
<lb n="150812"/><emph>Freeman's Urinal</emph> and <emph>Weekly Arsewipe</emph> here. Paralyse Europe. You which?
```

Is it worth reopening the issue and reordering the tagging as follows?

```xml
<p><foreign xml:lang="la"><lb n="150077"/>Vidi aquam egredientem […]
<p><foreign xml:lang="la"><lb n="150170"/>Aurora borealis</foreign> or a steel foundry? […]
<emph><lb n="150812"/>Freeman's Urinal</emph> and […]
```

I did a quick compute and there are about 23 instances of `<foreign>` and nine of `<emph>` in the episode that would be effected. I think that would be everything then, wouldn’t it? Are there any other elements even used in the markup yet?

**Comment by JonathanReeve** [comment]
Cool. I just swapped `<foreign>`s and `<emph>`s with `<lb>`s in 58d741a above.
